default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sk8higher
  password: c00lpass
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: hospital_development

test:
  <<: *default
  database: hospital_test

production:
  <<: *default
  database: hospital
